import { useEffect, useState } from "react";

import Layout from "../components/layout/Layout";
import TopicTree from "../components/study/TopicTree";
import TopicContent from "../components/study/TopicContent";

import { extractTopics } from "../services/studyApi";

function Study() {

    const [topics, setTopics] = useState([]);
    const [selectedTopic, setSelectedTopic] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadTopics();
    }, []);

    async function loadTopics() {

        try {

            const data = await extractTopics();

            console.log(data);

            // Convert backend response into frontend format
            const flatTopics = [];

            let id = 1;

            data.topics.forEach(unit => {

                unit.topics.forEach(title => {

                    flatTopics.push({
                        id: id++,
                        title,
                        completed: false,
                        difficulty: "Medium",
                        summary: "Summary will be generated by AI later."
                    });

                });

            });

            setTopics(flatTopics);

            if (flatTopics.length > 0) {
                setSelectedTopic(flatTopics[0]);
            }

        } catch (err) {

            console.error(err);

        }

        setLoading(false);
    }

    const toggleTopic = (id) => {

        const updatedTopics = topics.map(topic =>
            topic.id === id
                ? { ...topic, completed: !topic.completed }
                : topic
        );

        setTopics(updatedTopics);

        const updatedSelected = updatedTopics.find(
            topic => topic.id === selectedTopic?.id
        );

        if (updatedSelected) {
            setSelectedTopic(updatedSelected);
        }

    };

    if (loading) {
        return (
            <Layout>
                <h2 className="text-2xl font-semibold">
                    Loading Topics...
                </h2>
            </Layout>
        );
    }

    return (

        <Layout>

            <div className="grid grid-cols-12 gap-6">

                <div className="col-span-4">

                    <TopicTree
                        topics={topics}
                        selectedTopic={selectedTopic}
                        onTopicSelect={setSelectedTopic}
                        onToggle={toggleTopic}
                    />

                </div>

                <div className="col-span-8">

                    <TopicContent
                        topic={selectedTopic}
                    />

                </div>

            </div>

        </Layout>

    );

}

export default Study;